name: 'LicenseLint Action'
description: 'Run LicenseLint on project'

inputs:
  author:
    description: 'The author of your project'
    required: true
  email:
    description: 'The email of the author (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: install licenselint
      run: cargo install licenselint-cli
      shell: bash
    - name: run licenselint
      run: |
        if [ -n "${{ inputs.email }}" ]; then
          licenselint --author "${{ inputs.author }}" --email "${{ inputs.email }}" check
        else
          licenselint --author "${{ inputs.author }}" check
        fi
      shell: bash
